config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
  	resources :ingredients
  end
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :recipe
	
	validates :name, :amount, :measure, presence: true
	validates_inclusion_of :measure, :in => ['c', 'tbsp', 'tsp', 'lb', 'oz', 'g', 'ea'] #same as /_form
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
	
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def index
	end
	
	def show
	end
	
	def new
		@ingredient = Ingredient.new
		@recipe = Recipe.find(params[:recipe_id])
	end
	
	def edit
		@ingredient = Ingredient.find(params[:id])
		@recipe = Recipe.find(params[:recipe_id])
	end
	
	def create 
		@ingredient = Ingredient.new(ingredient_params)
		@recipe = Recipe.find(params[:recipe_id]) #check params with partial form, just listed as id?
		@ingredient.recipe_id = @recipe.id

		respond_to do |format|
      if @ingredient.save(ingredient_params)
        format.html { redirect_to edit_recipe_path @recipe, notice: 'ingredient was successfully added.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
	end
	
	def update
		@ingredient = Ingredient.find(params[:id])
		recipe = Recipe.find(params[:recipe_id])
		 respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to edit_recipe_path(recipe), notice: 'ingredient was successfully updated.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
	end
	
	def destroy
		ingredient = Ingredient.find(params[:id])
		recipe = Recipe.find(params[:recipe_id])
		ingredient.destroy
		respond_to do |format|
      format.html { redirect_to edit_recipe_path(recipe), notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	private
		def ingredient_params
				params.require(:ingredient).permit(:name, :amount, :measure)
		end
end	

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :gather_ingredients, only: [:show, :edit]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @ingredients = @recipe.ingredients.order('id ASC')
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = @recipe.ingredients.order('id ASC')
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to edit_recipe_path(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    @ingredients = @recipe.ingredients
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def gather_ingredients
      @ingredients = @recipe.ingredients.order('id ASC')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      # params.fetch(:recipe, {})
      params.require(:recipe).permit(:name, :instructions, :yield)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_username(params[:sessions][:username])
		if user && user.authenticate(params[:sessions][:password])
			session[:user_id] = user.id
			redirect_to '/'
			flash[:success] = "Nom Nom Nom"
		else
			redirect_to '/login'
			flash[:error] = "None Shall Pass"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

	def logged_in?
		session[:user_id]
	end

	def current_user
		User.find_by_id(session[:user_id])
	end

	def is_admin?(user)
		User.find_by_id(user.id)
	end
end

app/views/ingredients/_form.html.erb
<%= form_for [recipe, ingredient] do |f| %>
  <% if ingredient.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>
  
    <ul>
    <% ingredient.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    
  <div class="actions">
    <%= f.label 'name', class: 'form-label' %> 
    <%= f.text_field :name, class: 'form-field' %> 
    <%= f.label 'amount', class: 'form-label' %> 
    <%= f.number_field :amount, step: 0.01, class: 'form-field' %>
    <%= f.label 'measurement', class: 'form-label' %> 
    <%= f.select :measure, ['c', 'tbsp', 'tsp', 'lb', 'oz', 'g', 'ea'],{}, {class: 'form-field ingredient-measure dropdown'}%> 
    <%= f.submit "Add to pot", class: 'form-btn btn'%>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<li>
	<%= ingredient.amount %>
	<%= ingredient.measure %>
	<%= ingredient.name %>
	<%= link_to "-", [:edit,@recipe,ingredient]%>
	<%= link_to "x", [@recipe,ingredient], method: :delete %>
</li>

app/views/ingredients/edit.html.erb
<div class='form-container'>
  <section class='form'>
    <%= render 'form', recipe: @recipe, ingredient: @ingredient %>
  <section>
</div>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', recipe_path(@recipe) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chefbot</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Dancing+Script|Shadows+Into+Light');
    </style>
  </head>

  <body>
    <div class='header'></div>
    <%= javascript_tag do %>
      if (document.body.offsetWidth <= 1199) {
       document.getElementsByClassName('header')[0].insertAdjacentHTML("beforeend", "<%= j render 'shared/mobile_header' %>");
      } else {
       document.getElementsByClassName('header')[0].insertAdjacentHTML("beforeend", "<%= j render 'shared/header' %>");
      }
    <% end %>
    <%= render 'shared/menu' %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="form"> 
  <%= form_for(recipe) do |f| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
        <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      
    <div class="actions field-container">
        <%= f.label "Name", class: 'form-label' %> 
        <%= f.text_field :name, class: 'form-field' %>
        <br>
        <% if Recipe.exists?(recipe.id) %>
          <%= f.label "Yield", class: 'form-label' %> 
          <%= f.number_field :yield, class: 'form-field'%> 
          <%= f.label "Instructions", class: 'form-label instructions-label' %> 
          <%= f.text_area :instructions, class: 'recipe-instructions form-field' %>
        <% end %>
        <br>
        <%= f.submit "Create Recipe", class: 'form-btn btn'%>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class='form-container'>
  <%= render 'form', recipe: @recipe %>

  <% if Recipe.exists?(@recipe.id) %>
    <section class='form'>
      <%= render partial: "ingredients/form", locals: {recipe: @recipe, ingredient: Ingredient.new } %>
      <ul class="ingredient-list"><%= render @ingredients %></ul>
    </section>
  <% end %>
</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>
<div>
  <ul class='recipe-list'>
    <% @recipes.each do |recipe| %>
      <li class='recipe-list-item'><%= link_to recipe.name, recipe, class: 'recipe-name' %>
      <% if logged_in? && is_admin?(current_user) %>
        <section class='edit-menu'>
          <%= link_to image_tag('edit.png', class: 'edit'), edit_recipe_path(recipe) %>
          <%= link_to image_tag('delete.png', class: 'delete'), recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
        </section>
      </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class='form-container'>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/show.html.erb
<% if logged_in? && is_admin?(current_user) %>
	<section class='show-menu'>
		<%= link_to image_tag('edit.png', class: 'show-edit'), edit_recipe_path(@recipe), class: "nav-link" %>
	</section> 
<% end %>
<div class="intro">
	<h2 class="name">
		<%= @recipe.name %>
	</h2>

	<div class="recipe-feeds">
		<section class="yield">
			<p>Feeds: </p>
			<p><%= @recipe.yield %></p>
		</section>

		<section class="scale">
			<p>Scale: </p>
			<%= select_tag :scale, options_for_select(1..10), class: 'dropdown' %>
		</section>
	</div>
</div>

<div class="details">
	<section class="ingredients"> 
		<table>
			<tr>
				<th>Ingredient</th>
				<th colspan="2">Amount</th>
			</tr>
			<% @ingredients.each do |ingredient| %>
			<tr>
				<td><%= ingredient.name %></td>
				<td class="amount"><%= ingredient.amount %></td>
				<td><%= ingredient.measure %></td>
			</tr>
			<% end %>
		</table>
	</section>
	
	<section class="instructions">
		<%= simple_format(@recipe.instructions) %>
	</section>
</div>

app/views/shared/_header.html.erb
<nav class='btn-container'>
  <%= link_to 'Back', :back, class: 'header-btn back-btn' %>
</nav>
<section class='title-section'>
  <%= link_to 'ChefBot', root_path, class: 'title' %>
</section>
<nav class='nav-menu'>
  <p class='header-btn menu-btn'>Menu</p>
</nav>

app/views/shared/_menu.html.erb
<div class='menu hidden'>
  <% if logged_in? && is_admin?(current_user) %>
    <%= link_to image_tag('chefHat.png', alt: 'create recipe', class: 'create-recipe'), new_recipe_path, class: 'menu-link' %>
    <%= link_to image_tag('logout.png', class: 'logout'), logout_path, class: 'menu-link' %>
  <% else %>
    <%= link_to image_tag('login.png', class: 'login'), login_path, class: 'menu-link' %>
  <% end %>
</div>

app/views/shared/_mobile_header.erb
<nav>
  <%= link_to image_tag('back.png', class: 'back'), 'javascript:history.back()', class: 'nav-link' %>
</nav>
<section class='title-section'>
  <%= link_to 'ChefBot', root_path, class: 'title' %>
</section>
<nav class='nav-menu'>
  <%= image_tag('hamburger.png', alt: 'menu button', class: "menu-btn nav-link") %>
</nav>